/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.82
 * Generated at: 2019-07-01 06:52:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.egovframework.com.uat.uia;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class EgovGpkiIssu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

 /**
  * @Class Name : EgovGpkiIssu.jsp
  * @Description : 인증서 안내화면
  * @Modification Information
  * @
  * @  수정일         수정자                   수정내용
  * @ -------    --------    ---------------------------
  * @ 2009.03.25    박지욱          최초 생성
  *
  *  @author 공통서비스 개발팀 박지욱
  *  @since 2009.03.25
  *  @version 1.0
  *  @see
  *
  */

      out.write("\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" type=\"text/css\">\n");
      out.write("<title>MOPAS GPKI 인증서 안내</title>\n");
      out.write("<script>\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("  <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("    <tr>\n");
      out.write("      <td height=\"20\">&nbsp;</td>\n");
      out.write("    </tr>\n");
      out.write("    <tr>\n");
      out.write("\t  <td align=\"left\" valign=\"top\">\n");
      out.write("\n");
      out.write("\t    <!-- 인증서소개 시작 -->\n");
      out.write("\t\t<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" width=\"572\" style=\"margin:27 0 0 21;\">\n");
      out.write("    \t<!--하나씩-->\n");
      out.write("        <tr>\n");
      out.write("          <td>\n");
      out.write("          <img src=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\" width=\"131\" height=\"13\"><br>\n");
      out.write("          <div style=\"margin-top:15px;\" align=\"justify\">“행정전자서명 인증서”라 함은 행정전자서명이 진정한 것임을 확인ㆍ증명할 수 있도록 하기 위하여 행정기관, 보조기관, 보좌기관, 전자문서유통 및 행정정보 공공이용, 공공기반, 은행 또는 사용자에게   발급하는 전자적 정보를 말한다.<br />\n");
      out.write("            <br />\n");
      out.write("            전자거래시 인증서를 사용하면 신원확인, 문서의 위·변조, 거래사실의 부인 방지 등의 효과를 얻을 수   있습니다. 인증서에는 인증서 버전, 인증서 일련번호, 인증서의 유효기간, 발급기관명 및 전자서명 알고리즘 정보, 가입자 이름 및 신원확인정보 등이 포함되어 있다.</div>          </td>\n");
      out.write("        </tr>\n");
      out.write("        <!--//하나씩-->\n");
      out.write("        <tr>\n");
      out.write("          <td height=\"30\"></td>\n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("          <td height=\"1\" bgcolor=\"#ECECEC\"></td>\n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("          <td height=\"30\"></td>\n");
      out.write("        </tr>\n");
      out.write("        <!--하나씩-->\n");
      out.write("        <tr>\n");
      out.write("          <td>\n");
      out.write("            <table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" width=\"572\">\n");
      out.write("              <tr>\n");
      out.write("                <td>\n");
      out.write("            <img src=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\" width=\"97\" height=\"13\"><br>\n");
      out.write("            <div style=\"margin-top:15px;\" align=\"justify\">행정전자서명 인증서 발급대상은 다음의 2가지로 분류된다.<br />\n");
      out.write("              <strong>첫째</strong>는 인증관리체계상 인증업무수행 인증기관, 등록기관, 원격등록기관에 해당하는 행정기관이 대상이며<br />\n");
      out.write("              <strong>둘째</strong>는 정보화시스템에 적용하기 위한 행정기관,   보조기관, 보좌기관, 공무원 그리고 해당 공무원과 행정기관, 보조기관, 보좌기관에서 관리하는 정보통신 장비가 일반 인증서 발급 대상이다.<br />\n");
      out.write("              <strong>셋째</strong>는 전자문서 유통 및 행정정보 공동이용 공공기관, 은행법으로 지정된 기관과 사용자가 발급대상이다. </div>               </td>\n");
      out.write("            </tr>\n");
      out.write("            </table>          </td>\n");
      out.write("        </tr>\n");
      out.write("        <!--//하나씩-->\n");
      out.write("        <tr>\n");
      out.write("          <td height=\"30\"></td>\n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("          <td height=\"1\" bgcolor=\"#ECECEC\"></td>\n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("          <td height=\"30\"><a name=\"wire01\" id=\"wire01\"></a></td>\n");
      out.write("        </tr>\n");
      out.write("        <!--하나씩-->\n");
      out.write("        <tr>\n");
      out.write("          <td>\n");
      out.write("          <img src=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\" width=\"72\" height=\"13\"><br>\n");
      out.write("            <table width=\"572\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"margin-top:15;\">\n");
      out.write("              <tr>\n");
      out.write("                <td>\n");
      out.write("                  <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("                    <tr>\n");
      out.write("\t\t\t\t      <td height=\"10\">&nbsp;</td>\n");
      out.write("\t\t\t\t    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                    <td width=\"15\" align=\"left\"><img src=\"");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write("\" width=\"9\" height=\"13\" alt=\"개요모양아이콘이미지\"/></td>\n");
      out.write("                    <td><b><font color=\"#649E0E\">인증/등록기관 인증서</font></b></td>\n");
      out.write("                    </tr>\n");
      out.write("                  </table>                </td>\n");
      out.write("              </tr>\n");
      out.write("              <tr>\n");
      out.write("                <td>\n");
      out.write("                  <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("                    <tr>\n");
      out.write("                    <td colspan=\"5\" bgcolor=\"#DFF0C7\" height=\"1\"></td>\n");
      out.write("                    </tr>\n");
      out.write("                     <tr>\n");
      out.write("                    <td bgcolor=\"#DFF0C7\" width=\"1\"></td>\n");
      out.write("                    <td width=\"117\" align=\"center\" bgcolor=\"#F3F9EA\"><b><font color=\"#74AA23\">최상위 인증기관</font></b></td>\n");
      out.write("                    <td bgcolor=\"#DFF0C7\" width=\"1\"></td>\n");
      out.write("                    <td width=\"452\" align=\"left\"><div style=\"margin:6px;\">인증관리센터는 행정전자서명 인증업무 수행 등에 활용하도록 최상위인증기관에 인증서를 발급합니다.</div></td>\n");
      out.write("                    <td bgcolor=\"#DFF0C7\" width=\"1\"></td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                    <td colspan=\"5\" bgcolor=\"#DFF0C7\" height=\"1\"></td>\n");
      out.write("                    </tr>\n");
      out.write("                     <tr>\n");
      out.write("                    <td bgcolor=\"#DFF0C7\" width=\"1\"></td>\n");
      out.write("                    <td width=\"117\" align=\"center\" bgcolor=\"#F3F9EA\"><b><font color=\"#74AA23\">인증기관용</font></b></td>\n");
      out.write("                    <td bgcolor=\"#DFF0C7\" width=\"1\"></td>\n");
      out.write("                    <td width=\"452\" align=\"left\"><div style=\"margin:6px;\">인증관리센터는 안전행전부 장관이 지정ㆍ고시하는 정부인증기관을 대상으로 인증업무 수행등에 활용하도록 인증서를 발급합니다.</div></td>\n");
      out.write("                    <td bgcolor=\"#DFF0C7\" width=\"1\"></td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                    <td colspan=\"5\" bgcolor=\"#DFF0C7\" height=\"1\"></td>\n");
      out.write("                    </tr>\n");
      out.write("                     <tr>\n");
      out.write("                    <td bgcolor=\"#DFF0C7\" width=\"1\"></td>\n");
      out.write("                    <td width=\"117\" align=\"center\" bgcolor=\"#F3F9EA\"><b><font color=\"#74AA23\">등록기관용</font></b></td>\n");
      out.write("                    <td bgcolor=\"#DFF0C7\" width=\"1\"></td>\n");
      out.write("                    <td width=\"452\" align=\"left\"><div style=\"margin:6px;\">인증관리센터는 등록기관 등록업무 수행 등에 활용하도록 등록기관 지정 행정기관에 인증서를 발급합니다.</div></td>\n");
      out.write("                    <td bgcolor=\"#DFF0C7\" width=\"1\"></td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                    <td colspan=\"5\" bgcolor=\"#DFF0C7\" height=\"1\"></td>\n");
      out.write("                    </tr>\n");
      out.write("                  </table>                </td>\n");
      out.write("              </tr>\n");
      out.write("            </table>          </td>\n");
      out.write("        </tr>\n");
      out.write("        <!--//하나씩-->\n");
      out.write("        <tr>\n");
      out.write("          <td height=\"30\"></td>\n");
      out.write("        </tr>\n");
      out.write("        <!--하나씩-->\n");
      out.write("        <tr>\n");
      out.write("          <td>\n");
      out.write("            <table width=\"572\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n");
      out.write("              <tr>\n");
      out.write("                <td>\n");
      out.write("                  <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("                    <tr>\n");
      out.write("                    <td width=\"15\" align=\"left\"><img src=\"");
      if (_jspx_meth_c_005furl_005f5(_jspx_page_context))
        return;
      out.write("\" width=\"9\" height=\"13\" alt=\"개요모양아이콘이미지\"/></td>\n");
      out.write("                    <td><b><font color=\"#649E0E\">기관/개인 인증서</font></b></td>\n");
      out.write("                    </tr>\n");
      out.write("                  </table>                </td>\n");
      out.write("              </tr>\n");
      out.write("              <tr>\n");
      out.write("                <td>\n");
      out.write("                  <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"1\" bgcolor=\"#DFF0C7\">\n");
      out.write("                    <tr>\n");
      out.write("                    <td align=\"center\" width=\"100\" bgcolor=\"#F3F9EA\" rowspan=\"3\"><b><font color=\"#74AA23\">기관 </font></b></td>\n");
      out.write("                    <td width=\"100\" height=\"25\" align=\"center\" bgcolor=\"#FFFFFF\"><strong>기관용</strong></td>\n");
      out.write("                    <td bgcolor=\"#ffffff\"><div style=\"margin:6px;\">인증관리센터는 사무관리규정에 따라 관인을 가질수 있는 행정기관, 보조기관, 보좌기관등의 과단위까지의 1개의 기관용   인증서를 발급합니다.</div> </td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                    <td height=\"45\" align=\"center\" bgcolor=\"#FFFFFF\"><strong>특수목적용</strong></td>\n");
      out.write("                    <td bgcolor=\"#ffffff\" height=\"45\"><div style=\"margin:6px;\">인증관리센터는 사무관리규정에 따라 행정기관의 업무를 관인과 같이 처리할 수 없도록 규정한   특수관인을 관리하는 경우에 특수목적용 인증서를 발급합니다.</div></td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                    <td align=\"center\" bgcolor=\"#FFFFFF\" height=\"45\"><strong>서버용</strong></td>\n");
      out.write("                    <td bgcolor=\"#ffffff\"><div style=\"margin:6px;\">인증관리센터는 행정기관에서 관리해야할 책임이 있는 정보통신 장비가 일정 규칙에 의해 정보통신 장비가 지속적으로   행정업무를 처리하고자 하는 경우에 서버 단위로 인증서를 발급합니다.</div> </td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                    <td align=\"center\" bgcolor=\"#F3F9EA\"><b><font color=\"#74AA23\">개인</font></b></td>\n");
      out.write("                    <td bgcolor=\"#ffffff\" colspan=\"2\" height=\"45\"><div style=\"margin:6px;\">인증관리센터는 행정기관 소속 공무원이 사용자인증 및 전자결재, 보안메일 등의   행정업무 또는 전자상거래 등에서 활용하도록 하기 위해 부처별 개인단위로 인증서를 발급합니다.</div></td>\n");
      out.write("                    </tr>\n");
      out.write("                  </table>               </td>\n");
      out.write("              </tr>\n");
      out.write("              <tr>\n");
      out.write("                <td><div style=\"margin-top:10px;\">※ 기타 : 행정업무 처리에서 필요하다고 판단되는 경우 인증협의회 또는 관련 기관과 협의하여 업무에 맞는 인증서를 발급할 수 있습니다.</div> </td>\n");
      out.write("              </tr>\n");
      out.write("            </table>          </td>\n");
      out.write("        </tr>\n");
      out.write("        <!--//하나씩-->\n");
      out.write("        <tr>\n");
      out.write("          <td height=\"30\"></td>\n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("          <td height=\"1\" bgcolor=\"#ECECEC\"></td>\n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("          <td height=\"30\"></td>\n");
      out.write("        </tr>\n");
      out.write("        <!--하나씩-->\n");
      out.write("        <tr>\n");
      out.write("          <td>\n");
      out.write("            <table width=\"572\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n");
      out.write("              <tr>\n");
      out.write("                <td><img src=\"");
      if (_jspx_meth_c_005furl_005f6(_jspx_page_context))
        return;
      out.write("\" width=\"111\" height=\"13\"><br>\n");
      out.write("                  <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" style=\"margin-top:15px;\">\n");
      out.write("                    <tr>\n");
      out.write("                    <td width=\"15\" align=\"left\"><img src=\"");
      if (_jspx_meth_c_005furl_005f7(_jspx_page_context))
        return;
      out.write("\" width=\"9\" height=\"13\" alt=\"개요모양아이콘이미지\"/></td>\n");
      out.write("                    <td><b><font color=\"#649E0E\">인증/등록기관 </font></b></td>\n");
      out.write("                    </tr>\n");
      out.write("                  </table>                </td>\n");
      out.write("              </tr>\n");
      out.write("              <tr>\n");
      out.write("                <td>\n");
      out.write("                  <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"1\" bgcolor=\"#DFF0C7\">\n");
      out.write("                    <tr bgcolor=\"#e8f9f4\">\n");
      out.write("                    <td align=\"center\" bgcolor=\"#F3F9EA\" height=\"30\"><b><font color=\"#74AA23\">구분</font></b></td>\n");
      out.write("                    <td align=\"center\" bgcolor=\"#F3F9EA\"><b><font color=\"#74AA23\">ou명</font></b></td>\n");
      out.write("                    <td align=\"center\" bgcolor=\"#F3F9EA\"><b><font color=\"#74AA23\">cn명</font></b></td>\n");
      out.write("                    <td align=\"center\" bgcolor=\"#F3F9EA\"><b><font color=\"#74AA23\">DN명(예)</font></b></td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr bgcolor=\"#ffffff\">\n");
      out.write("                    <td width=\"100\" height=\"25\"><div style=\"margin:6px;\">최상위 인증기관</div></td>\n");
      out.write("                    <td width=\"100\"><div style=\"margin:6px;\">ou=GPKI</div></td>\n");
      out.write("                    <td><div style=\"margin:6px;\">cn=Root   CA</div></td>\n");
      out.write("                    <td><div style=\"margin:6px;\">cn=Root   CA, ou=GPKI, o=Government of Korea,c=KR</div></td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr bgcolor=\"#ffffff\">\n");
      out.write("                    <td><div style=\"margin:6px;\">인증기관</div></td>\n");
      out.write("                    <td><div style=\"margin:6px;\">ou=GPKI</div></td>\n");
      out.write("                    <td><div style=\"margin:6px;\">cn=CA   + 기관코드(7) + 일련번호(2)</div></td>\n");
      out.write("                    <td><div style=\"margin:6px;\">cn=CA131000001,   ou=GPKI, o=Government of Korea,c=KR</div></td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr bgcolor=\"#ffffff\">\n");
      out.write("                    <td><div style=\"margin:6px;\">등록기관</div></td>\n");
      out.write("                    <td><div style=\"margin:6px;\">cn=해당인증기관,<br />\n");
      out.write("                      ou=GPKI<br /></div></td>\n");
      out.write("                    <td><div style=\"margin:6px;\">cn=RA   + 기관코드(7) + 일련번호(2)</div></td>\n");
      out.write("                    <td><div style=\"margin:6px;\">cn=RA131000001,cn=CA131000001,   ou=GPKI, o=Government of Korea,c=KR</div></td>\n");
      out.write("                    </tr>\n");
      out.write("                    </table>               </td>\n");
      out.write("              </tr>\n");
      out.write("            </table>          </td>\n");
      out.write("        </tr>\n");
      out.write("        <!--//하나씩-->\n");
      out.write("        <tr>\n");
      out.write("          <td height=\"30\"></td>\n");
      out.write("        </tr>\n");
      out.write("        <!--하나씩-->\n");
      out.write("        <tr>\n");
      out.write("          <td>\n");
      out.write("            <table width=\"572\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n");
      out.write("              <tr>\n");
      out.write("                <td>\n");
      out.write("                  <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("                    <tr>\n");
      out.write("                    <td width=\"15\" align=\"left\"><img src=\"");
      if (_jspx_meth_c_005furl_005f8(_jspx_page_context))
        return;
      out.write("\" width=\"9\" height=\"13\" alt=\"개요모양아이콘이미지\"/></td>\n");
      out.write("                    <td><b><font color=\"#649E0E\">기관/개인 </font></b></td>\n");
      out.write("                    </tr>\n");
      out.write("                  </table>                </td>\n");
      out.write("              </tr>\n");
      out.write("              <tr>\n");
      out.write("                <td>\n");
      out.write("                  <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"1\" bgcolor=\"#DFF0C7\">\n");
      out.write("                    <tr bgColor=\"#F3F9EA\">\n");
      out.write("                    <td align=\"center\" bgColor=\"#F3F9EA\" colSpan=\"2\" height=\"30\"><b><font color=\"#74AA23\">구분</font></b></td>\n");
      out.write("                    <td align=\"center\" bgcolor=\"#F3F9EA\"><b><font color=\"#74AA23\">ou명</font></b></td>\n");
      out.write("                    <td align=\"center\" bgcolor=\"#F3F9EA\"><b><font color=\"#74AA23\">cn명</font></b></td>\n");
      out.write("                    <td align=\"center\" bgcolor=\"#F3F9EA\">\n");
      out.write("                      <table cellSpacing=\"0\" cellPadding=\"0\" border=\"0\">\n");
      out.write("                        <tr>\n");
      out.write("                          <td><b><font color=\"#74AA23\">DN명</font></b></td>\n");
      out.write("                        </tr>\n");
      out.write("                      </table>\n");
      out.write("                      </td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr bgColor=\"#ffffff\">\n");
      out.write("                    <td width=\"50\" rowSpan=\"2\" align=\"center\" bgcolor=\"#ffffff\">기관 </td>\n");
      out.write("                    <td width=\"80\" height=\"25\" align=\"center\" bgcolor=\"#ffffff\">기관용</td>\n");
      out.write("                    <td width=\"100\"><div style=\"margin:6px;\">ou=최하위기관명, ou=상위기관명, ou=최상위기관명</div></td>\n");
      out.write("                    <td align=\"middle\"><div style=\"margin:6px;\">-</div></td>\n");
      out.write("                    <td><div style=\"margin:6px;\">ou=보안관리팀,   ou=전자정부본부, ou=안전행전부, o=Government of Korea, c=KR</div></td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr bgColor=\"#ffffff\">\n");
      out.write("                    <td align=\"center\" bgcolor=\"#ffffff\">서버용</td>\n");
      out.write("                    <td><div style=\"margin:6px;\">ou=Group   of Server</div></td>\n");
      out.write("                    <td><div style=\"margin:6px;\">cn=SVR   + 기관코드(7) + 일련번호(3)</div></td>\n");
      out.write("                    <td><div style=\"margin:6px;\">cn=SVR131000001,   ou=Group of Server, o=Government of Korea, c=KR</div></td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr bgColor=\"#ffffff\">\n");
      out.write("                    <td align=\"center\" bgcolor=\"#ffffff\">개인 </td>\n");
      out.write("                    <td align=\"center\" bgcolor=\"#ffffff\">&nbsp;</td>\n");
      out.write("                    <td><div style=\"margin:6px;\">ou=people,   ou=최상위기관명</div></td>\n");
      out.write("                    <td><div style=\"margin:6px;\">cn=기관구분자(3)   + 이름 + 일련번호(3)<BR>\n");
      out.write("                      *일련번호:동명이인 </div></td>\n");
      out.write("                    <td><div style=\"margin:6px;\">cn=001홍길동001,   ou=people, ou=안전행전부, o=Government of Korea, c=KR</div></td>\n");
      out.write("                    </tr>\n");
      out.write("                  </table>               </td>\n");
      out.write("             </tr>\n");
      out.write("            </table>          </td>\n");
      out.write("        </tr>\n");
      out.write("        <!--//하나씩-->\n");
      out.write("      </table>\n");
      out.write("      <!-- 인증서소개 끝 -->\n");
      out.write("\n");
      out.write("\t  </td>\n");
      out.write("    </tr>\n");
      out.write("  </table>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/jsp/egovframework/com/uat/uia/EgovGpkiIssu.jsp(27,29) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/css/egovframework/com/com.css");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /WEB-INF/jsp/egovframework/com/uat/uia/EgovGpkiIssu.jsp(45,20) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/images/egovframework/com/uat/uia/01_t01.gif");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /WEB-INF/jsp/egovframework/com/uat/uia/EgovGpkiIssu.jsp(66,22) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/images/egovframework/com/uat/uia/01_t02.gif");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f3_reused = false;
    try {
      _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f3.setParent(null);
      // /WEB-INF/jsp/egovframework/com/uat/uia/EgovGpkiIssu.jsp(87,20) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f3.setValue("/images/egovframework/com/uat/uia/01_t03.gif");
      int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
      if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      _jspx_th_c_005furl_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f3, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f4_reused = false;
    try {
      _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f4.setParent(null);
      // /WEB-INF/jsp/egovframework/com/uat/uia/EgovGpkiIssu.jsp(96,58) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f4.setValue("/images/egovframework/com/uat/uia/icon01.gif");
      int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
      if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      _jspx_th_c_005furl_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f4, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f5_reused = false;
    try {
      _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f5.setParent(null);
      // /WEB-INF/jsp/egovframework/com/uat/uia/EgovGpkiIssu.jsp(153,58) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f5.setValue("/images/egovframework/com/uat/uia/icon01.gif");
      int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
      if (_jspx_th_c_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      _jspx_th_c_005furl_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f5, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f6 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f6_reused = false;
    try {
      _jspx_th_c_005furl_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f6.setParent(null);
      // /WEB-INF/jsp/egovframework/com/uat/uia/EgovGpkiIssu.jsp(200,30) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f6.setValue("/images/egovframework/com/uat/uia/01_t04.gif");
      int _jspx_eval_c_005furl_005f6 = _jspx_th_c_005furl_005f6.doStartTag();
      if (_jspx_th_c_005furl_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
      _jspx_th_c_005furl_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f6, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f7 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f7_reused = false;
    try {
      _jspx_th_c_005furl_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f7.setParent(null);
      // /WEB-INF/jsp/egovframework/com/uat/uia/EgovGpkiIssu.jsp(203,58) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f7.setValue("/images/egovframework/com/uat/uia/icon01.gif");
      int _jspx_eval_c_005furl_005f7 = _jspx_th_c_005furl_005f7.doStartTag();
      if (_jspx_th_c_005furl_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f7);
      _jspx_th_c_005furl_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f7, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f8 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f8_reused = false;
    try {
      _jspx_th_c_005furl_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f8.setParent(null);
      // /WEB-INF/jsp/egovframework/com/uat/uia/EgovGpkiIssu.jsp(252,58) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f8.setValue("/images/egovframework/com/uat/uia/icon01.gif");
      int _jspx_eval_c_005furl_005f8 = _jspx_th_c_005furl_005f8.doStartTag();
      if (_jspx_th_c_005furl_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f8);
      _jspx_th_c_005furl_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f8, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f8_reused);
    }
    return false;
  }
}
